### PR TITLE
Add API docs

### LINKED ISSUE #5: API documentation
Would be nice to have online sphinx (api) documentation on readthedocs that can be linked to using intersphinx.

### PR DESCRIPTION
**Pull request by thijstriemstra**
- use tox to test against multiple python versions
- add sphinx api documentation
- enforce pep8 style using flake8

fixes #5

### CODE REVIEW

**Comment by thijstriemstra** [comment]
This is a work in progress @kplindegaard, I'll let you know when it's ready for review.

**Comment by kplindegaard** [comment]
Looking forward to it. Thanks!

**Comment by thijstriemstra** [comment]
@kplindegaard I see many methods with a comment before the docstring like this:

```
    def open(self, bus):
        # type: (int) -> None
        """
        Open a given i2c bus.
        :param bus: i2c bus number (e.g. 0 or 1)
        """
        self.fd = os.open("/dev/i2c-{}".format(bus), os.O_RDWR)
        self.funcs = self._get_funcs()
```

e.g. ` # type: (int) -> None`. Unfortunately this seems to screw up Sphinx, can I move those below the docstring instead?

**Comment by kplindegaard** [comment]
Go ahead. Could alternatively be deleted and we could add type hints in the docstring itself.

**Comment by thijstriemstra** [comment]
> Go ahead. Could alternatively be deleted and we could add type hints in the docstring itself.

I'll move them below the docstring and then you can later review them and move it into docstring.

**Comment by kplindegaard** [comment]
👍

**Comment by thijstriemstra** [comment]
@kplindegaard this PR should be ready to go.

**Comment by thijstriemstra** [comment]
ps. i would squash merge this..

**Comment by kplindegaard** [comment]
I hid some parts i don't think will be very relevant for the normal user and published the documentation on [Read the docs](http://smbus2.readthedocs.io)
@thijstriemstra: Thank you for the great job you did!

**Pull request merged**
