### PR TITLE
add support for write_byte

### PR DESCRIPTION
**Pull request by cyboflash**
changes after comments

### CODE REVIEW

**Comment by arunderwood** [comment]
I've never used Python and I2C together so I was shopping for a library and happened on smbus2.  I was sad to see the lack of write_byte support and was about to move on, but 💥 I saw this 2 hour old PR and rejoiced.

TL;DR, I'm using the code in this PR and it's working perfectly 👍

**Comment by cyboflash** [comment]
@kplindegaard I see that it hasn't been merged. Were there any issues that you saw?

**Comment by kplindegaard** [comment]
@cyboflash: No issues now. Unable to merge the final PR after review changes.

**Comment by kplindegaard** [comment]
And of course. Thanks, @cyboflash :+1:

**Comment by cyboflash** [comment]
@kplindegaard Did you say you were unable to merge? Did you mean that you were able to merge it?

**Comment by kplindegaard** [comment]
@cyboflash No no. Nothing technical. Unable as in no time to attend this before now. Other duties first, such as sleep, work, family birthday party, walk the dog etc.

**Comment by kplindegaard** [comment]
@cyboflash and @arunderwood I implemented read_byte too to complement write_byte and tested it quickly to see if sequential reads byte by byte works. It did. New version (0.1.15) tagged and [published on PyPi](https://pypi.python.org/pypi/smbus2/0.1.5) tonight.

**Comment by arunderwood** [comment]
Excellent.  Thank you to the both of you.

**Pull request merged**
