### PR TITLE
Handle re-opening a closed bus

### PR DESCRIPTION
**Pull request by henrik-nil-acc**
Set address and _force_last to their initial values to be able to handle an open -> close -> open sequence.

### CODE REVIEW

**Comment by kplindegaard** [comment]
Hi @henrik-nil-acc. Just so I understand what the intent is: You want to keep the `SMBus` object alive also after a `close()`, I presume. Later, you open the bus again. Is it potential lack of setting the address on after subsequent `open()` call that causes problems for you?

**Comment by henrik-nil-acc** [comment]
@kplindegaard, correct. I'm thinking it's a valid use-case and from the existing code in close() it looks like it might been intended to be supported since self._pec is set to it's initial value.

**Comment by kplindegaard** [comment]
Fair point, thanks.

**Review by kplindegaard — APPROVED** [review]

**Comment by kplindegaard** [comment]
@henrik-nil-acc I'm on holiday but will make a new patch version soon.

**Pull request merged**
